language: crystal

crystal:
  - latest
  - nightly

jobs:
  allow_failures:
    - crystal: nightly

addons:
  apt:
    packages:
      - git

install:
  - shards install

script:
  - crystal spec
  - crystal tool format --check
  - bin/ameba
